### ISSUE TITLE
npm tests are broken

### ISSUE THREAD

**Issue by klutchell** [balena-os/leviathan-worker#37]
I tried to enable `npm run test` for CI but the spec files are way out-of-date and using TestBot interfaces that have changed.

**Comment by vipulgupta2048** [comment]
Looking into this now. There is no way to use leviathan-worker separately. Hence, having tests that check this component individually makes little sense. I say we delete the tests for leviathan-worker, and instead add tests for autokit-interface-sw and Qemu worker to make sure they work?

@klutchell what say?

**Comment by klutchell** [comment]
@vipulgupta2048 I think there is always benefit to having both unit tests, in addition to integration tests. But if they are broken they aren't doing anyone any good so I'm okay to remove them if fixing them is more lift.

**Comment by vipulgupta2048** [comment]
Cool, my angle is more like even if we fix these - these tests won't be helpful. I haven't ran them in the past 3 years and they predate our QEMU and autokit worker. Components we should be writing tests for.

**Comment by klutchell** [comment]
SGTM
